FROM python:3.12.0-slim

# Set working directory
# WORKDIR /app

# Copy and install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Copy over source code
COPY /app ./app

# Setup an app user so the container doesn't run as the root user
RUN useradd app
USER app

# Run
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]